#! /bin/bash

# echo Installing crudini
# sudo apt-get update
# sudo apt-get install -y crudini

# echo Installing makepasswd
# sudo apt-get install -y makepasswd

# sample_enc_pass = U2FsdGVkX1+wYpUB6pxgAQaviqC7oBrtdHObihVraYzCz3SDlvSSjDa321+6QMzZ

ST2_MONGODB_PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 24 ; echo '')
# ST2_MONGODB_PASSWORD=$(makepasswd --char 24 --count 1)

# generating random key for password
PWD_KEY=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 18 ; echo '')


# openssl genrsa -out key.txt 2048

# encrypt "hello world" using the RSA key in key.txt
# echo "${ST2_MONGODB_PASSWORD}" | openssl rsautl -inkey key.txt -encrypt >output.bin

# decrypt the message and output to stdout
# openssl rsautl -inkey key.txt -decrypt <output.bin

# echo ${PWD_KEY}

# ST2_MONGOD_ENCRYPTED_PWD=$(makepasswd --char 24 --count 1 | openssl enc -aes-256-cbc -base64 -pbkdf2 -pass pass:${PWD_KEY})

# echo ${ST2_MONGODB_PASSWORD}

ST2_MONGOD_ENCRYPTED_PWD=`echo ${ST2_MONGODB_PASSWORD} | openssl enc -aes-256-cbc -base64 -pbkdf2 -pass pass:${PWD_KEY}`

echo ${ST2_MONGOD_ENCRYPTED_PWD}

# sudo crudini --set /etc/st2/pswd.conf keys db_key "${PWD_KEY}"

# sudo crudini --set /etc/st2/sstt.conf database password "${ST2_MONGOD_ENCRYPTED_PWD}"

# DB_GET_KEY=$(sudo crudini --get /etc/st2/pswd.conf keys db_key)

# # echo ${DB_GET_KEY}

# ST2_MONGOD_ENC_GET_PWD=$(sudo crudini --get /etc/st2/sstt.conf database password)

# # echo ${ST2_MONGOD_ENC_GET_PWD}

# FINAL_DECRYPTED_PASSWORD=`echo ${ST2_MONGOD_ENC_GET_PWD} | openssl enc -aes-256-cbc -base64 -d -pbkdf2 -pass pass:${DB_GET_KEY}`
# echo ${FINAL_DECRYPTED_PASSWORD}
