#! /bin/bash

PASSWORD_KEY=$(sudo crudini --get /etc/st2/st2.conf keys secret_key)

ST2_MONGOD_ENC_PWD=$(sudo crudini --get /etc/st2/st2.conf database password)

MONGODB_PASSWORD=`echo ${ST2_MONGOD_ENC_PWD} | openssl enc -aes-256-cbc -base64 -d -pbkdf2 -pass pass:${PASSWORD_KEY}`

echo "MongoDB Password: ${MONGODB_PASSWORD}"
